apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-demo
  namespace: calc
  labels:
    app: k3s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
      - name: k3s-demo
        image: gocalculator:latest
        env:
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: secret.data
                key: secretPort
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
 name: k3s-demo
 namespace: calc
spec:
 type: LoadBalancer
 selector:
   app: k3s-demo
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: secret.data
type: Opaque
stringData:
  secretPort: "3000"